name: first_project
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/imagelogin.png
